version: "2.2"
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - ./database/dataset:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sreality
    networks:
      - app_network
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/sreality?sslmode=disable
    depends_on:
      - postgres
    networks:
      - app_network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app_network
networks:
  app_network:
    driver: bridge